### ISSUE TITLE
Usage with time series data

### ISSUE THREAD

**Issue by brunofacca** [atif-hassan/PyImpetus#4]
Hello. This library looks very interesting, thanks for sharing it!

Have you tested it with any time series dataset? If so, did it perform well? 

I was also wondering if it makes sense to use this library as a second step in feature selection, where the first step would be PCMCI (amongst others, in an ensemble). Any thoughts?

Thank you!

**Comment by atif-hassan** [comment]
This feature selection algorithm works with tabular data only (classification/regression). Time-series dataset has a time axis, making the data 3 dimensional and therefore incompatible with PyImpetus.

**Comment by brunofacca** [comment]
Thank you for the reply, but I'm confused. Time-series data is tabular. We have a table where one column contains timestamps, and another column (or multiple columns, for a multivariate time series) contains the values. 

Additionally, I'm not using time-series models like ARIMA. I'm using classifiers like LightGBM. For my use case, the engineered features contain all the look-back data that I need, so we could even discard the timestamps entirely.

**Comment by atif-hassan** [comment]
Ah yes, then it'd definitely work! And yes, you can also use PyImpetus in an ensemble since you can get feature importance scores out of it. It's not available at the moment, but I am going to update the package within this week as I am writing the corresponding paper.

**Comment by brunofacca** [comment]
I'm glad to hear that. Looking forward to the new version :). Thanks again!

**Comment by atif-hassan** [comment]
The new version is now available at pypi and I have updated the repo accordingly with tutorials and comparisons. Do let me know if and how this works out for you. Always open to feedback :)

**Comment by brunofacca** [comment]
Hi Atif. Thank you for letting me know! I will soon experiment with it and let you know how it goes :)
