### ISSUE TITLE
Facing exception while processing 1 Million data..

### ISSUE THREAD

**Issue by aswinjose89** [atif-hassan/PyImpetus#5]
Refer the exception below

```
A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9), SIGKILL(-9)}
```
@atif-hassan

**Comment by atif-hassan** [comment]
If n_jobs > 1 then PyImpetus internally makes that many copies of the data. You can try setting n_jobs to 1 in order to stop PyImpetus from making multiple copies of the data. This will make the algorithm slower but you shouldn't run into above said error.

**Comment by aswinjose89** [comment]
Thanks for the quick response..

**Comment by atif-hassan** [comment]
Please note that "n_jobs>1" case also includes "n_jobs=-1"

**Comment by aswinjose89** [comment]
Noted..I have tried n_jobs=70(cores) and  n_jobs=-1(To consume all the cores).Both cases were throwing similar exception..

**Comment by atif-hassan** [comment]
Yes, the reason being that with any value other than 1 for n_jobs will result in internal copies of the data which will definitely lead to memory error for such a large dataset.

**Comment by aswinjose89** [comment]
Thanks for the inputs
